In [1]:
import pandas as pd
import numpy as np

In [9]:
artist_df = pd.read_csv('../data/music_artist_w_details.csv')
artist_df.drop(columns=["Unnamed: 5"], inplace=True)
artist_df.columns

Index(['artist_name', 'artist_genre', 'artist_img', 'artist_id', 'country'], dtype='object')

In [10]:
artist_df[artist_df["artist_genre"].apply(lambda x: "rap" and "hip hop" in x)].head(15)

,artist_name,artist_genre,artist_img,artist_id,country
4,Eminem,"detroit hip hop, hip hop, rap",https://i.scdn.co/image/ab6761610000e5eba00b11...,7dGJo4pcD2V6oG8kP0tJRR,United States
6,Kanye West,"chicago rap, hip hop, rap",https://i.scdn.co/image/ab6761610000e5eb6e835a...,5K4W6rqBFWDnAN6FQUkS6x,United States
19,Gorillaz,"alternative hip hop, modern rock, rock",https://i.scdn.co/image/ab6761610000e5eb2c61d9...,3AA28KZvwAUcZuOKwyblJQ,United Kingdom
25,Artist Unknown,hip hop,https://i.scdn.co/image/ab67616d0000b273dea2d7...,6gjAbs229sNHhSskJpQ2mG,Ireland
27,Drake,"canadian hip hop, canadian pop, hip hop, pop r...",https://i.scdn.co/image/ab6761610000e5eb429338...,3TVXtAsR1Inumwj472S9r4,Canada
29,The black eyed peas karaok...,hip hop,https://media.istockphoto.com/id/1298261537/ve...,2H2XZw9jFlCL91K9DLGCyc,United States
35,JAY-Z,"east coast hip hop, gangster rap, hip hop, pop...",https://i.scdn.co/image/ab6761610000e5ebc75afc...,3nFkdlSjzX9mRTtwJOzDYB,United States
49,All Artist Blue Squad PAN,hip hop,https://i.scdn.co/image/ab67616d0000b2739df8da...,5OIXzogZi85GrRqWR1Uw9v,United Kingdom
51,Rage Against The Machine,"alternative metal, alternative rock, conscious...",https://i.scdn.co/image/ab6761610000e5ebda4bd2...,2d0hyoQ5ynDBnkvAbJKORj,United States
68,USHER,"atl hip hop, contemporary r&b, dance pop, pop,...",https://i.scdn.co/image/ab6761610000e5eb716114...,23zg3TcAtWQy7J6upgbUnj,United States
69,50 Cent,"east coast hip hop, gangster rap, hip hop, pop...",https://i.scdn.co/image/dd031b9c5d1b6eba4a691c...,3q7HBObVc0L8jNeTe5Gofh,United States
74,Robert Christopher Brown,hip hop,https://i.scdn.co/image/ab6761610000e5eba1a0f0...,6I63hpHYJGenpC1it1m0f4,United Kingdom
78,Artist Ko Ensemble,hip hop,https://media.istockphoto.com/id/1298261537/ve...,1SAObfwYJSC9qgMlCcUVRp,United States
83,Outkast,"atl hip hop, dirty south rap, hip hop, old sch...",https://i.scdn.co/image/ab6761610000e5eb0cb3f9...,1G9G7WwrXka3Z1r7aIDjI7,United States
86,Snoop Dogg,"g funk, gangster rap, hip hop, pop rap, rap, w...",https://i.scdn.co/image/ab6761610000e5eb9a3982...,7hJcb9fa4alzcOq3EaNPoG,United States

In [7]:
artist_df[artist_df["artist_genre"].apply(lambda x: "rap" and "hip hop" in x)].head(15)

,artist_name,artist_genre,artist_img,artist_id,country,Unnamed: 5
4,Eminem,"detroit hip hop, hip hop, rap",https://i.scdn.co/image/ab6761610000e5eba00b11...,7dGJo4pcD2V6oG8kP0tJRR,United States,NaN
6,Kanye West,"chicago rap, hip hop, rap",https://i.scdn.co/image/ab6761610000e5eb6e835a...,5K4W6rqBFWDnAN6FQUkS6x,United States,NaN
19,Gorillaz,"alternative hip hop, modern rock, rock",https://i.scdn.co/image/ab6761610000e5eb2c61d9...,3AA28KZvwAUcZuOKwyblJQ,United Kingdom,NaN
25,Artist Unknown,hip hop,https://i.scdn.co/image/ab67616d0000b273dea2d7...,6gjAbs229sNHhSskJpQ2mG,Ireland,NaN
27,Drake,"canadian hip hop, canadian pop, hip hop, pop r...",https://i.scdn.co/image/ab6761610000e5eb429338...,3TVXtAsR1Inumwj472S9r4,Canada,NaN
29,The black eyed peas karaok...,hip hop,https://media.istockphoto.com/id/1298261537/ve...,2H2XZw9jFlCL91K9DLGCyc,United States,NaN
35,JAY-Z,"east coast hip hop, gangster rap, hip hop, pop...",https://i.scdn.co/image/ab6761610000e5ebc75afc...,3nFkdlSjzX9mRTtwJOzDYB,United States,NaN
49,All Artist Blue Squad PAN,hip hop,https://i.scdn.co/image/ab67616d0000b2739df8da...,5OIXzogZi85GrRqWR1Uw9v,United Kingdom,NaN
51,Rage Against The Machine,"alternative metal, alternative rock, conscious...",https://i.scdn.co/image/ab6761610000e5ebda4bd2...,2d0hyoQ5ynDBnkvAbJKORj,United States,NaN
68,USHER,"atl hip hop, contemporary r&b, dance pop, pop,...",https://i.scdn.co/image/ab6761610000e5eb716114...,23zg3TcAtWQy7J6upgbUnj,United States,NaN
69,50 Cent,"east coast hip hop, gangster rap, hip hop, pop...",https://i.scdn.co/image/dd031b9c5d1b6eba4a691c...,3q7HBObVc0L8jNeTe5Gofh,United States,NaN
74,Robert Christopher Brown,hip hop,https://i.scdn.co/image/ab6761610000e5eba1a0f0...,6I63hpHYJGenpC1it1m0f4,United Kingdom,NaN
78,Artist Ko Ensemble,hip hop,https://media.istockphoto.com/id/1298261537/ve...,1SAObfwYJSC9qgMlCcUVRp,United States,NaN
83,Outkast,"atl hip hop, dirty south rap, hip hop, old sch...",https://i.scdn.co/image/ab6761610000e5eb0cb3f9...,1G9G7WwrXka3Z1r7aIDjI7,United States,NaN
86,Snoop Dogg,"g funk, gangster rap, hip hop, pop rap, rap, w...",https://i.scdn.co/image/ab6761610000e5eb9a3982...,7hJcb9fa4alzcOq3EaNPoG,United States,NaN